### ISSUE TITLE
Frontend to visualize and filter new orders and communities

### ISSUE THREAD

**Issue by grunch** [lnp2pBot/frontend#1]
As the number of users grows, we need to segment into groups, we call these groups [communities](https://lnp2pbot.com/learn/communities.html), the use of communities can be confusing for new users, for this reason we want to develop a tool that shows you information regarding the offers published in communities (and global orders) in a user-friendly way, a frontend which show all pending orders, allow to filter orders by currency and order type (buy/sell)

We already developed an very simple [API](https://github.com/lnp2pBot/rust-api) which have four endpoints:

1. GET /community/:id
2. GET /order/:id
3. GET /communities
4. GET /orders

1 returns a specific community which match with the id sent in the request, 2 returns a specific order which match with the id sent in the request. We can see examples here:

`http://api.lnp2pbot.com:3000/community/6272e7a47abf30829d545d45`

`http://api.lnp2pbot.com:3000/order/62e97950b486c326eae3d234`

3 and 4 are GET requests are query strings, here we have examples with curl:

```
# get all pending orders
$ curl -X GET "http://api.lnp2pbot.com:3000/orders"

# get pending buy orders with USD
$ curl -X GET "http://api.lnp2pbot.com:3000/orders?currency=USD&direction=buy"

# get all communities
$ curl -X GET "http://api.lnp2pbot.com:3000/communities"

# get communities that operates with EUR
$ curl -X GET "http://api.lnp2pbot.com:3000/communities?currency=EUR"
```

This data is not updated but is real data that can be used to create the frontend

### Orders's params
`/orders?<_id>&<direction>&<currency>&<community_id>`
### Communities's params
`/communities?<_id>&<currency>`

## Framework
The frontend should be developed on Iced, Dioxus, Reactjs or other frontend framework, if is **coded in 🦀 rust 🦀  (Iced or Dioxus) the reward will be increased by 50%** .

The user will have a view to see all the detail from each order and click on it, the link of the order will go to the channel where this order is located, for example:

```
{
  "_id": "62e97950b486c326eae3d234",
  "description": "Vendiendo sats\nPor 20 - 50 Bolívares 🇻🇪\nRecibo pago por pago móvil\nTiene 88 operaciones exitosas\n#SELLVES\nTasa: yadio.io +9%\n4.9 ⭐⭐⭐⭐⭐ (88)\n",
  "amount": 0,
  "fee": 0,
  "bot_fee": 0.006,
  "community_fee": 0.7,
  "status": "PENDING",
  "type": "sell",
  "fiat_amount": null,
  "fiat_code": "VES",
  "payment_method": "pago móvil",
  "taken_at": null,
  "tg_chat_id": null,
  "tg_order_message": null,
  "tg_channel_message1": "32522",
  "price_from_api": true,
  "price_margin": 9,
  "community_id": null,
  "created_at": "2022-08-02T19:21:52.505Z"
}
``` 
This is a global order, global orders are published on @p2plightning channel, we know this because `community_id = null`, so this link should go to https://t.me/$channel/$tg_channel_message1 => https://t.me/p2plightning/33304

## Community link
If the order is from a community we need to request data from that community, let's see another example:

```
  {
    "_id": "62eaa1e2f4a2be4c3b675d47",
    "description": "Comprando 1 sats\nPor 1 Pesos 🇨🇺\nPago por prueba\nTiene 2 operaciones exitosas\n#BUYCUP\nPrecio: 100.000.000\n",
    "amount": 1,
    "fee": 0,
    "bot_fee": 0.006,
    "community_fee": 0.7,
    "status": "PENDING",
    "type": "buy",
    "fiat_amount": 1,
    "fiat_code": "CUP",
    "payment_method": "prueba",
    "taken_at": null,
    "tg_chat_id": null,
    "tg_order_message": null,
    "tg_channel_message1": "3",
    "price_from_api": false,
    "price_margin": 2,
    "community_id": "62ea9fe4f4a2be4c3b675a83",
    "created_at": "2022-08-03T16:27:14.816Z"
  }
```

In this we see that community_id = "62ea9fe4f4a2be4c3b675a83", so now we need to go to community endpoint

http://api.lnp2pbot.com:3000/community/6272e7a47abf30829d545d45

And we get this:
```
{
  "_id": "6272e7a47abf30829d545d45",
  "name": "ARS",
  "order_channels": [
    {
      "name": "@p2plightning_ARS",
      "type": "mixed"
    }
  ],
  "group": "@LNp2pBot_ARS",
  "fee": 1,
  "earnings": 397,
  "orders_to_redeem": 51,
  "dispute_channel": "@p2plightning_ARS_alert",
  "solvers": [
    {
      "username": "dolchi21"
    }
  ],
  "public": true,
  "currencies": [
    "ARS",
    "USD",
    "RSAT",
    "RBTC",
    "DAI",
    "USDT",
    "DOC",
    "BUSD"
  ],
  "created_at": "2022-05-04T20:52:52.108Z"
}

```
The field `order_channels` have one record with name `@p2plightning_ARS`, this is what we need to create our link, so this link should go to `https://t.me/$channel/$tg_channel_message1 => https://t.me/p2plightning_ARS/3`

Have in consideration that this community only have one channel for buy and sell orders, but some communities have a channel to buy and other to sell.

**Comment by bilthon** [comment]
Although possible, using a body to pass parameters for an HTTP GET request is usually discouraged. Is it too late now to change the API in that way? See [here](https://stackoverflow.com/questions/978061/http-get-with-request-body) for more info.

**Comment by grunch** [comment]
We can easily change that, what do you think is the best way for it?

**Comment by bilthon** [comment]
To use query parameters instead of the body.

**Comment by grunch** [comment]
ok, take it for granted

**Comment by bilthon** [comment]
Oh, and another thing, for the cases where this API will not be accessed from the same domain as the API (most of development and maybe even production really) it would be required to add this header in all responses:

```
Access-Control-Allow-Origin: *
```

To prevent CORS issues.

**Comment by grunch** [comment]
> To use query parameters instead of the body.

I just pushed this change and updated the curl examples with query strings

**Comment by grunch** [comment]
> Oh, and another thing, for the cases where this API will not be accessed from the same domain as the API (most of development and maybe even production really) it would be required to add this header in all responses:
> 
> ```
> Access-Control-Allow-Origin: *
> ```
> 
> To prevent CORS issues.

This is done too

**Comment by grunch** [comment]
This is done, thanks @bilthon for this great job!!! 🤖
